language: cpp
matrix:
  include:
  - name: Test Ubuntu 16.04 + gcc-7 + codecov + sonarcloud
    os: linux
    addons:
      apt:
        sources:
        - ubuntu-toolchain-r-test
        packages:
        - g++-7
      sonarcloud:
        organization: hyp3rflow
        token:
          secure: "hYrIAj6vNKDVATRxv9bMQFs0zltwwz7gnqmaGqgSXMO5cyw8yBytKB6Ri866+F9p/y0GWL8R8E9h4oixWz6AeCeZ3Ni6iJXLsmBxJ53b4CHvrvEnbovWtQQz7WqrrrtULhpyAEHVE4bX4wg9773U3Y75xitvYWreCGQOZTofagsLLxO1Vq73luMlG/uE1smd06MDvWpgxXhg2PO1bwBgcPQtEXn4x+OpwgviBt1jDbOH3FUyyx1U4RLYy/y/bw8CX/4Qn6t9zF38KFD/ibge+Ku+P4KLu0Wymytf6URYU83kP31JcL60Ghltxe1t0lzJVpjHSDChVr3Ic7lvA78yF4qWZpC1AgmTYBxf2Yb12kwpQlwLw/zlX7EbSabZkcEp/SUV4y2MskZnBd4yCeyj/qQkfZfb8yeEDdqDSyzGu1BmiiUGYt+cNMwpgiFko/MhCoCD7E89nQWNtcircGXSpq8KJzIghArzqTRILezEzCDEi4Kc2/q6M+83zNJVOKdE1aWyvYXljhKhFuj8W4clzDJ6HNaeefh6pWYinyPcNCnn6gDrDGlEWHZFarQMY9vy0y4jTkQcvmqVgNfGkf6MG+OwEpRChEcf51az0JrKhCv4cOP3clAMDQtLyMwXhLTiksGvx/4Ao2fAJydZgUmDHyrgKziQSBN8p+/oaReHzwM="
    dist: xenial
    sudo: required
    compiler: gcc
    env:
    - BUILD_TYPE=Debug
    script:
    - sh Scripts/travis_build_codecov_sonar.sh
  - name: Ubuntu 18.04 LTS + gcc
    os: linux
    dist: bionic
    sudo: required
    compiler: gcc
    script:
    - sh Scripts/travis_build.sh
  - name: Test OS X 10.14 + Xcode 10.2 + clang
    os: osx
    osx_image: xcode10.2
    compiler: clang
    script:
    - sh Scripts/travis_build.sh
  before_install:
  - eval "${MATRIX_EVAL}"

