language: cpp
matrix:
  include:
  - name: Test Ubuntu 16.04 + gcc-7 + codecov + sonarcloud
    os: linux
    addons:
      apt:
        sources:
        - ubuntu-toolchain-r-test
        packages:
        - g++-7
      sonarcloud:
        organization: "hyp3rflow"
        token:
          secure: "csbVnYZsQM/G1wwkj0r1G07Rv1DXVwKYLyKMX77qqliT3aP9MdwC6dTVNCe67pIL0XPfikRjW/KZe0vQ53HPxIIkqn4AXsD1547e37sqTCgPx6QqyZ7NRyjIZgJqh/XiXwTB2savz30k8YJqEJUrgnPRZN5RgizkN1GNI1I0dEm0ijmvI4/MrJYUMM7koA6wgqj1A/FtlngFxlMw15i1KacP2SSmwjpFd+y0fNOYoPg2u9kfETll8tSWshDqSuJH8TXvC/3O2WUMSKENo60Wdw+5Q9WPVlSNDtzrFgyDER0b9lesU9tgodroXUyQUbr3X1Eqskk0wTE+qDzLozJyRHqDEvtWeCkouBBjrk7ZZt+itb2CNOl250q0zaQOLr6UkYwQYonRdcGIRdpwfW/UQM09qGKqNczjrnPsry96oHpF9RqhohTkwjEpBXufe3Gp4q/AtqwnhwaHmoHwQbb4+JWE/LKbrJzHTHro2l/XUvNlaB2keBCBoaVVsEwIaujJlIK5MYaUFDMeVEtBc5J6gYDyqnAbIkd3QPe9LohwhdZYLqp1imSy7poaGcsZ9BQNaRPVCECrESvzKD+KMJFa61Y6rnsbckR25/nEs0k7CQ/9soHsTVxlYmt0F5Bnv4rKOG9RGOXNsho4NRwziaT8SN0iOS8VfD+rO78Nr7CZwxY="
    dist: xenial
    sudo: required
    compiler: gcc
    env:
    - BUILD_TYPE=Debug
    script:
    - sh Scripts/travis_build_codecov_sonar.sh
  - name: Ubuntu 18.04 LTS + gcc
    os: linux
    dist: bionic
    sudo: required
    compiler: gcc
    script:
    - sh Scripts/travis_build.sh
  - name: Test OS X 10.14 + Xcode 10.2 + clang
    os: osx
    osx_image: xcode10.2
    compiler: clang
    script:
    - sh Scripts/travis_build.sh
  before_install:
  - eval "${MATRIX_EVAL}"

